FROM fedora:latest

ARG USERNAME=dev
ARG USER_UID=1000
ARG USER_GID=$USER_UID

ENV SDKMAN_DIR=/opt/$USERNAME/sdkman
ENV ANDROID_HOME=/opt/$USERNAME/android_sdk
ENV PATH=$PATH:$ANDROID_HOME/platform-tools:$FLUTTER/bin

RUN dnf update -y && dnf install -y \
  git \
  nodejs \
  sudo \
  unzip \
  zip

RUN groupadd --gid $USER_GID $USERNAME
RUN useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME
RUN echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME && chmod 0440 /etc/sudoers.d/$USERNAME

RUN mkdir /opt/$USERNAME

RUN npm i -g n yarn cordova
RUN n 16

RUN curl -s "https://get.sdkman.io?rcupdate=false" | bash
RUN source /opt/$USERNAME/sdkman/bin/sdkman-init.sh && \
  sdk install java 11.0.12-open && \
  sdk install gradle 7.6
RUN echo "source /opt/$USERNAME/sdkman/bin/sdkman-init.sh" >> /etc/profile
RUN echo "source /opt/$USERNAME/sdkman/bin/sdkman-init.sh" >> /etc/bashrc

RUN curl -o /tmp/cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9123335_latest.zip
RUN unzip /tmp/cmdline-tools.zip -d /opt/$USERNAME
RUN source /opt/$USERNAME/sdkman/bin/sdkman-init.sh && \
  echo "y" | /opt/$USERNAME/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME "build-tools;32.0.0" && \
  echo "y" | /opt/$USERNAME/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME "platforms;android-32" && \
  echo "y" | /opt/$USERNAME/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME "platform-tools"

RUN chown -R $USERNAME:$USERNAME /opt/$USERNAME

USER $USERNAME